- name: Install and configure MySQL
  hosts: dbserver
  become: yes
  gather_facts: false
  vars:
    new_mysql_root_password: supersecretpassW0rd)!
    mysqlsoftware:
      - mysql-server
      - mysql-client
  tasks:
    - name: Update and upgrade system
      shell: apt update && apt upgrade -y

    - name: install python, pip etc
      shell: apt install -y "{{ item }}"
      with_items:
        - pip 
        - python3-dev 
        - default-libmysqlclient-dev 
        - build-essential

    - name: Install MySQL server
      shell: apt install mysql-server -y

    - name: Install MySQL client
      shell: apt install -y mysql-client

    - name: pip install mysqlclient
      shell: pip install mysqlclient

    - name: Copy MySQL configuration file
      copy:
        src: ./dbserver/my.cnf
        dest: /etc/mysql/my.cnf
        owner: root
        group: root
        mode: 0600

    - name: Start the MySQL service
      service:
        name: mysql
        state: started

    - name: update mysql root password for all root accounts
      mysql_user:
        name: root
        host: localhost
        password: "{{ new_mysql_root_password }}"

    - name: delete anonymous MySQL server user for localhost
      action: mysql_user user="" state="absent"

    - name: remove the MySQL test database
      action: mysql_db db=test state=absent