bridge:
  hosts:
    bridge.vagrant: 
        ansible_host: 192.168.100.2
        ansible_ssh_private_key_file: /Users/angryfossa/Desktop/Hashicorp/Vagrant/HillelIT/.vagrant/machines/bridge/virtualbox/private_key
