---
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s8:
      addresses:
        - 192.168.100.3/24
      routes:
        - to: 0.0.0.0/0
          via: 192.168.100.4
    enp0s9:
      addresses:
        - 192.168.101.3/24
      routes:
        - to: 192.168.102.0/24
          via: 192.168.100.4