---
network:
    version: 2
    renderer: networkd
    ethernets:
        enp0s8:
            dhcp4: true
            match:
                macaddress: 08:00:27:53:3a:8e
        enp0s9:
            addresses:
            - 192.168.100.2/24
            routes:
            - to: 192.168.101.0/24
              via: 192.168.100.3
            - to: 192.168.102.0/24
              via: 192.168.100.4